### ISSUE TITLE
Add a defaultMandrillMessage

### ISSUE THREAD

**Issue by basvandijk** [adinapoli/mandrill#23]
Hey Alfredo,

It would be nice if there was a `defaultMandrillMessage :: MandrillMessage` so that you don't need to construct this huge record.

Adding a [Default](http://hackage.haskell.org/package/data-default-0.5.3/docs/Data-Default.html#t:Default) instance for `MandrillMessage` would be another possibility.

**Comment by adinapoli** [comment]
Hey Bas,

yes, that's sounds a very reasonable request. I might be leaning on going with your first proposal, as it's in line on what other library does and lately `data-default` has been under "attack" (Cannot find the relevant blog post, it was on Reddit a while ago).

Would you be interested in sending a PR in?

**Comment by basvandijk** [comment]
> Would you be interested in sending a PR in?

Yes will do.

It will probably take the `from_email` as a parameter since that seems to be required:
```haskell
defaultMandrillMessage :: MandrillEmail -> MandrillMessage
```

**Comment by adinapoli** [comment]
Yes, I think that would be ideal! ultimately the user would need at least
to supply a couple of emails for the default message to make sense; all the
rest can be defaulted to their monoidal empty value, when possible.

**Comment by basvandijk** [comment]
Haha I see you already provide [emptyMessage](http://hackage.haskell.org/package/mandrill-0.4.1.0/docs/Network-API-Mandrill.html#v:emptyMessage) which does everything I need. I somehow missed that.

**Comment by adinapoli** [comment]
Argh, dumb me for not having pointed you to that in the first place! I guess this is what happens to reply to GH issues in the evening from an iPad :wink:
