### ISSUE TITLE
sending appears to be broken?

### ISSUE THREAD

**Issue by mwotton** [adinapoli/mandrill#26]
using the code

```
let Just email = Text.Email.Validate.emailAddress "mwotton@gmail.com" in
runMandrill "APIKEY_REDACTED" $ sendEmail $ newTextMessage email [email] "a message to you" "<html>an html message to you</html>"
```
Full Request
```
{
    "async": true,
    "key": "APIKEY_REDACTED",
    "ip_pool": null,
    "message": {
        "images": {},
        "signing_domain": null,
        "subject": "a message to you",
        "track_opens": null,
        "preserve_recipients": null,
        "return_path_domain": null,
        "attachments": {},
        "inline_css": null,
        "url_strip_qs": null,
        "subaccount": null,
        "auto_text": null,
        "text": "<html>an html message to you</html>",
        "to": [
            {
                "email": "mwotton@gmail.com",
                "name": null,
                "type": null
            }
        ],
        "from_name": null,
        "recipient_metadata": {},
        "merge_vars": {},
        "google_analytics_campaign": null,
        "google_analytics_domains": {},
        "headers": null,
        "view_content_link": null,
        "metadata": null,
        "auto_html": null,
        "html": "<html>an html message to you</html>",
        "global_merge_vars": {},
        "track_clicks": null,
        "from_email": "mwotton@gmail.com",
        "tracking_domain": null,
        "merge": null,
        "bcc_address": null,
        "important": null,
        "tags": {}
    },
    "send_at": null
}
```
Full Response
```
[
    {
        "email": "mwotton@gmail.com",
        "status": "rejected",
        "_id": "119f97f724874c1ba1741034df891dae",
        "reject_reason": "unsigned"
    }
]
```

**Comment by adinapoli** [comment]
Hi Mark, this is an excerpt from the Mandrill documentation I think it's relevant to you:

If you signed up for a Mandrill account on or after December 1st, 2015, you must add SPF and DKIM records and verify ownership of your sending domains before you can send email through your account. Mandrill will not send any email from unverified domains or domains without valid SPF and DKIM records, including public domains like gmail.com, yahoo.com, and more.

Custom signing domains are only available to Mandrill accounts created before December 1st, 2015. If you signed up for a new Mandrill account on or after December 1st, 2015, the signing_domain parameter will be ignored.

Mail sent from unverified domains or domains without valid SPF and DKIM records will be rejected with the reject_reason, unsigned.

Learn more about SPF and DKIM, and domain verification

I wasn't aware of such new constrain from Mandrill, so I will make sure to update the README so people don't get confused.

**Comment by mwotton** [comment]
Ah, thank you! That was confusing.

**Comment by adinapoli** [comment]
No problem, I thought it was confusing as well. Please let me know if fixing the issue on Mandrill side let you deliver emails, so I can close this ticket. Feel also free to send me a PR which extends the README which any info you think will be useful to save the next person pain & confusion. Thanks!

**Comment by mwotton** [comment]
only other thing is that perhaps mandrill could catch it as a MandrillError, rather than this confusing message?

```
*** Exception: user error (Array (fromList [Object (fromList [("email",String "mwotton@gmail.com"),("status",String "rejected"),("_id",String "b5a10eb0fb4944b1aec11682565a3ca9"),("reject_reason",String "unsigned")])]) is neither a MandrillSuccess or a MandrillError.)
```

**Comment by adinapoli** [comment]
@mwotton agreed, error handling could be made more user friendly ;)

**Comment by mwotton** [comment]
after digging a bit, it looks like this is actually considered a MandrillSuccess, because it returns a list of responses, which may include a rejection. The root error is that there was no RR_Unsigned arm in your MandrillRejectReason datatype: i have added one and a test, and it appears a bit more helpful now.

**Comment by mwotton** [comment]
this does raise the question of whether it is better to fail noisily like it did, or to say "hey, there was a success, because i got a list of rejections". still, that's a question for you, and you are already cleaving closely to their error structure, so i'll just augment it. PR incoming.
